[2025-05-27T19:50:04.107+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:49:56+00:00 [queued]>
[2025-05-27T19:50:04.113+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:49:56+00:00 [queued]>
[2025-05-27T19:50:04.113+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T19:50:04.121+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_inventory_returns> on 2025-05-27 19:49:56+00:00
[2025-05-27T19:50:04.126+0000] {standard_task_runner.py:57} INFO - Started process 1731 to run task
[2025-05-27T19:50:04.131+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'generate_inventory_returns', 'manual__2025-05-27T19:49:56+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmp5jo0ohts']
[2025-05-27T19:50:04.139+0000] {standard_task_runner.py:85} INFO - Job 326: Subtask generate_inventory_returns
[2025-05-27T19:50:04.178+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:49:56+00:00 [running]> on host d80f98a6628f
[2025-05-27T19:50:04.718+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='generate_inventory_returns' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T19:49:56+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T19:49:56+00:00'
[2025-05-27T19:50:04.719+0000] {logging_mixin.py:154} INFO - Starting inventory and returns data generation...
[2025-05-27T19:50:04.720+0000] {logging_mixin.py:154} INFO - Retrieving existing data for inventory and returns generation...
[2025-05-27T19:50:04.746+0000] {logging_mixin.py:154} INFO - Generating inventory data...
[2025-05-27T19:50:04.786+0000] {logging_mixin.py:154} INFO - Loaded 500 inventory records to ods_inventory
[2025-05-27T19:50:04.788+0000] {logging_mixin.py:154} INFO - Generating returns data...
[2025-05-27T19:50:04.812+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/walmart_etl_dag.py", line 105, in etl_generate_inventory_returns
    result = generate_inventory_returns_data()
  File "/opt/airflow/walmart-etl/generate_inventory_returns_data.py", line 244, in main
    returns_data = generate_returns_data(existing_data, num_records=200)
  File "/opt/airflow/walmart-etl/generate_inventory_returns_data.py", line 228, in generate_returns_data
    df_returns.to_sql('ods_returns', engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^

[SQL: INSERT INTO ods_returns (return_id, return_date, product_id, store_id, reason_code, return_amount, quantity_returned, return_condition, original_sale_id, original_sale_date, source_system, load_timestamp) VALUES (%(return_id)s, %(return_date)s, %(product_id)s, %(store_id)s, %(reason_code)s, %(return_amount)s, %(quantity_returned)s, %(return_condition)s, %(original_sale_id)s, %(original_sale_date)s, %(source_system)s, %(load_timestamp)s)]
[parameters: ({'return_id': 'RET000001', 'return_date': datetime.date(2025, 5, 13), 'product_id': '6a12a9bf-202c-428c-8', 'store_id': 'Racine_Wisconsin_53402', 'reason_code': 'LATE', 'return_amount': Decimal('155.94'), 'quantity_returned': 3, 'return_condition': 'Like New', 'original_sale_id': 'SALE52392', 'original_sale_date': datetime.date(2025, 4, 29), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796505)}, {'return_id': 'RET000002', 'return_date': datetime.date(2025, 5, 3), 'product_id': '1aca5260-19b2-486b-b', 'store_id': 'Scranton_Pennsylvania_18504', 'reason_code': 'DEFECT', 'return_amount': Decimal('149.45'), 'quantity_returned': 5, 'return_condition': 'New', 'original_sale_id': 'SALE96698', 'original_sale_date': datetime.date(2025, 4, 20), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796532)}, {'return_id': 'RET000003', 'return_date': datetime.date(2025, 5, 14), 'product_id': '4e43c516-d6e5-49fd-9', 'store_id': 'Rio Rancho_New Mexico_87124', 'reason_code': 'DEFECT', 'return_amount': Decimal('106.32'), 'quantity_returned': 3, 'return_condition': 'Used', 'original_sale_id': 'SALE13385', 'original_sale_date': datetime.date(2025, 4, 20), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796551)}, {'return_id': 'RET000004', 'return_date': datetime.date(2025, 5, 14), 'product_id': 'b134b47d-9514-4718-b', 'store_id': 'Pasadena_Texas_77506', 'reason_code': 'DAMAGE', 'return_amount': Decimal('177.72'), 'quantity_returned': 4, 'return_condition': 'Used', 'original_sale_id': 'SALE27562', 'original_sale_date': datetime.date(2025, 4, 21), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796569)}, {'return_id': 'RET000005', 'return_date': datetime.date(2025, 4, 30), 'product_id': '013e5436-9767-46e1-a', 'store_id': 'Mandan_North Dakota_58554', 'reason_code': 'PERF', 'return_amount': Decimal('352.38'), 'quantity_returned': 2, 'return_condition': 'Used', 'original_sale_id': 'SALE43224', 'original_sale_date': datetime.date(2025, 4, 8), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796615)}, {'return_id': 'RET000006', 'return_date': datetime.date(2025, 5, 10), 'product_id': 'aa73de3b-e074-45eb-a', 'store_id': 'El Dorado Hills_California_95630', 'reason_code': 'OTHER', 'return_amount': Decimal('19.92'), 'quantity_returned': 4, 'return_condition': 'Like New', 'original_sale_id': 'SALE21161', 'original_sale_date': datetime.date(2025, 5, 2), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796653)}, {'return_id': 'RET000007', 'return_date': datetime.date(2025, 5, 8), 'product_id': '70d70198-4aa6-4cbf-8', 'store_id': 'Thousand Oaks_California_91360', 'reason_code': 'OTHER', 'return_amount': Decimal('604.90'), 'quantity_returned': 5, 'return_condition': 'Damaged', 'original_sale_id': 'SALE86133', 'original_sale_date': datetime.date(2025, 4, 14), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796662)}, {'return_id': 'RET000008', 'return_date': datetime.date(2025, 5, 25), 'product_id': '43ddd58f-f4d1-4a24-a', 'store_id': 'Davenport_Iowa_52803', 'reason_code': 'PERF', 'return_amount': Decimal('36.44'), 'quantity_returned': 4, 'return_condition': 'Defective', 'original_sale_id': 'SALE98185', 'original_sale_date': datetime.date(2025, 4, 27), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796669)}  ... displaying 10 of 200 total bound parameter sets ...  {'return_id': 'RET000199', 'return_date': datetime.date(2025, 5, 22), 'product_id': 'cc4013da-9705-4b39-a', 'store_id': 'Fairfield_Connecticut_6824', 'reason_code': 'WRONG', 'return_amount': Decimal('25.98'), 'quantity_returned': 2, 'return_condition': 'Defective', 'original_sale_id': 'SALE12026', 'original_sale_date': datetime.date(2025, 5, 20), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 797767)}, {'return_id': 'RET000200', 'return_date': datetime.date(2025, 5, 13), 'product_id': '8671c0ad-3556-41e3-b', 'store_id': 'Rochester_Minnesota_55901', 'reason_code': 'CHANGE', 'return_amount': Decimal('5.02'), 'quantity_returned': 1, 'return_condition': 'Damaged', 'original_sale_id': 'SALE82760', 'original_sale_date': datetime.date(2025, 4, 17), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 797772)})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-05-27T19:50:04.822+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=walmart_etl_dag, task_id=generate_inventory_returns, execution_date=20250527T194956, start_date=20250527T195004, end_date=20250527T195004
[2025-05-27T19:50:04.830+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 326 for task generate_inventory_returns ((psycopg2.errors.UndefinedColumn) column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^

[SQL: INSERT INTO ods_returns (return_id, return_date, product_id, store_id, reason_code, return_amount, quantity_returned, return_condition, original_sale_id, original_sale_date, source_system, load_timestamp) VALUES (%(return_id)s, %(return_date)s, %(product_id)s, %(store_id)s, %(reason_code)s, %(return_amount)s, %(quantity_returned)s, %(return_condition)s, %(original_sale_id)s, %(original_sale_date)s, %(source_system)s, %(load_timestamp)s)]
[parameters: ({'return_id': 'RET000001', 'return_date': datetime.date(2025, 5, 13), 'product_id': '6a12a9bf-202c-428c-8', 'store_id': 'Racine_Wisconsin_53402', 'reason_code': 'LATE', 'return_amount': Decimal('155.94'), 'quantity_returned': 3, 'return_condition': 'Like New', 'original_sale_id': 'SALE52392', 'original_sale_date': datetime.date(2025, 4, 29), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796505)}, {'return_id': 'RET000002', 'return_date': datetime.date(2025, 5, 3), 'product_id': '1aca5260-19b2-486b-b', 'store_id': 'Scranton_Pennsylvania_18504', 'reason_code': 'DEFECT', 'return_amount': Decimal('149.45'), 'quantity_returned': 5, 'return_condition': 'New', 'original_sale_id': 'SALE96698', 'original_sale_date': datetime.date(2025, 4, 20), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796532)}, {'return_id': 'RET000003', 'return_date': datetime.date(2025, 5, 14), 'product_id': '4e43c516-d6e5-49fd-9', 'store_id': 'Rio Rancho_New Mexico_87124', 'reason_code': 'DEFECT', 'return_amount': Decimal('106.32'), 'quantity_returned': 3, 'return_condition': 'Used', 'original_sale_id': 'SALE13385', 'original_sale_date': datetime.date(2025, 4, 20), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796551)}, {'return_id': 'RET000004', 'return_date': datetime.date(2025, 5, 14), 'product_id': 'b134b47d-9514-4718-b', 'store_id': 'Pasadena_Texas_77506', 'reason_code': 'DAMAGE', 'return_amount': Decimal('177.72'), 'quantity_returned': 4, 'return_condition': 'Used', 'original_sale_id': 'SALE27562', 'original_sale_date': datetime.date(2025, 4, 21), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796569)}, {'return_id': 'RET000005', 'return_date': datetime.date(2025, 4, 30), 'product_id': '013e5436-9767-46e1-a', 'store_id': 'Mandan_North Dakota_58554', 'reason_code': 'PERF', 'return_amount': Decimal('352.38'), 'quantity_returned': 2, 'return_condition': 'Used', 'original_sale_id': 'SALE43224', 'original_sale_date': datetime.date(2025, 4, 8), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796615)}, {'return_id': 'RET000006', 'return_date': datetime.date(2025, 5, 10), 'product_id': 'aa73de3b-e074-45eb-a', 'store_id': 'El Dorado Hills_California_95630', 'reason_code': 'OTHER', 'return_amount': Decimal('19.92'), 'quantity_returned': 4, 'return_condition': 'Like New', 'original_sale_id': 'SALE21161', 'original_sale_date': datetime.date(2025, 5, 2), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796653)}, {'return_id': 'RET000007', 'return_date': datetime.date(2025, 5, 8), 'product_id': '70d70198-4aa6-4cbf-8', 'store_id': 'Thousand Oaks_California_91360', 'reason_code': 'OTHER', 'return_amount': Decimal('604.90'), 'quantity_returned': 5, 'return_condition': 'Damaged', 'original_sale_id': 'SALE86133', 'original_sale_date': datetime.date(2025, 4, 14), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796662)}, {'return_id': 'RET000008', 'return_date': datetime.date(2025, 5, 25), 'product_id': '43ddd58f-f4d1-4a24-a', 'store_id': 'Davenport_Iowa_52803', 'reason_code': 'PERF', 'return_amount': Decimal('36.44'), 'quantity_returned': 4, 'return_condition': 'Defective', 'original_sale_id': 'SALE98185', 'original_sale_date': datetime.date(2025, 4, 27), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 796669)}  ... displaying 10 of 200 total bound parameter sets ...  {'return_id': 'RET000199', 'return_date': datetime.date(2025, 5, 22), 'product_id': 'cc4013da-9705-4b39-a', 'store_id': 'Fairfield_Connecticut_6824', 'reason_code': 'WRONG', 'return_amount': Decimal('25.98'), 'quantity_returned': 2, 'return_condition': 'Defective', 'original_sale_id': 'SALE12026', 'original_sale_date': datetime.date(2025, 5, 20), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 797767)}, {'return_id': 'RET000200', 'return_date': datetime.date(2025, 5, 13), 'product_id': '8671c0ad-3556-41e3-b', 'store_id': 'Rochester_Minnesota_55901', 'reason_code': 'CHANGE', 'return_amount': Decimal('5.02'), 'quantity_returned': 1, 'return_condition': 'Damaged', 'original_sale_id': 'SALE82760', 'original_sale_date': datetime.date(2025, 4, 17), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 50, 4, 797772)})]
(Background on this error at: https://sqlalche.me/e/14/f405); 1731)
[2025-05-27T19:50:04.863+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-27T19:50:04.898+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
