[2025-05-27T19:53:43.356+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:53:37+00:00 [queued]>
[2025-05-27T19:53:43.361+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:53:37+00:00 [queued]>
[2025-05-27T19:53:43.361+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T19:53:43.367+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_inventory_returns> on 2025-05-27 19:53:37+00:00
[2025-05-27T19:53:43.370+0000] {standard_task_runner.py:57} INFO - Started process 107 to run task
[2025-05-27T19:53:43.374+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'generate_inventory_returns', 'manual__2025-05-27T19:53:37+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmpu9c_a843']
[2025-05-27T19:53:43.377+0000] {standard_task_runner.py:85} INFO - Job 334: Subtask generate_inventory_returns
[2025-05-27T19:53:43.398+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:53:37+00:00 [running]> on host a552bff97440
[2025-05-27T19:53:43.632+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='generate_inventory_returns' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T19:53:37+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T19:53:37+00:00'
[2025-05-27T19:53:43.633+0000] {logging_mixin.py:154} INFO - Starting inventory and returns data generation...
[2025-05-27T19:53:43.633+0000] {logging_mixin.py:154} INFO - Retrieving existing data for inventory and returns generation...
[2025-05-27T19:53:43.646+0000] {logging_mixin.py:154} INFO - Generating inventory data...
[2025-05-27T19:53:43.677+0000] {logging_mixin.py:154} INFO - Loaded 500 inventory records to ods_inventory
[2025-05-27T19:53:43.677+0000] {logging_mixin.py:154} INFO - Generating returns data...
[2025-05-27T19:53:43.692+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/walmart_etl_dag.py", line 105, in etl_generate_inventory_returns
    result = generate_inventory_returns_data()
  File "/opt/airflow/walmart-etl/generate_inventory_returns_data.py", line 244, in main
    returns_data = generate_returns_data(existing_data, num_records=200)
  File "/opt/airflow/walmart-etl/generate_inventory_returns_data.py", line 228, in generate_returns_data
    df_returns.to_sql('ods_returns', engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^

[SQL: INSERT INTO ods_returns (return_id, return_date, product_id, store_id, reason_code, return_amount, quantity_returned, return_condition, original_sale_id, original_sale_date, source_system, load_timestamp) VALUES (%(return_id)s, %(return_date)s, %(product_id)s, %(store_id)s, %(reason_code)s, %(return_amount)s, %(quantity_returned)s, %(return_condition)s, %(original_sale_id)s, %(original_sale_date)s, %(source_system)s, %(load_timestamp)s)]
[parameters: ({'return_id': 'RET000001', 'return_date': datetime.date(2025, 4, 28), 'product_id': '26cf99d1-c6bd-461e-a', 'store_id': 'Albemarle_North Carolina_28001', 'reason_code': 'COLOR', 'return_amount': Decimal('25.12'), 'quantity_returned': 4, 'return_condition': 'New', 'original_sale_id': 'SALE91665', 'original_sale_date': datetime.date(2025, 4, 24), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682269)}, {'return_id': 'RET000002', 'return_date': datetime.date(2025, 5, 9), 'product_id': '284f26e1-172c-4007-a', 'store_id': 'Seguin_Texas_78155', 'reason_code': 'DEFECT', 'return_amount': Decimal('69.50'), 'quantity_returned': 5, 'return_condition': 'New', 'original_sale_id': 'SALE26945', 'original_sale_date': datetime.date(2025, 4, 11), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682277)}, {'return_id': 'RET000003', 'return_date': datetime.date(2025, 5, 21), 'product_id': 'edbadf2b-5c74-4ad2-a', 'store_id': 'State College_Pennsylvania_16801', 'reason_code': 'DAMAGE', 'return_amount': Decimal('504.45'), 'quantity_returned': 5, 'return_condition': 'Like New', 'original_sale_id': 'SALE58003', 'original_sale_date': datetime.date(2025, 5, 4), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682283)}, {'return_id': 'RET000004', 'return_date': datetime.date(2025, 5, 25), 'product_id': '4889f27d-999d-40f5-b', 'store_id': 'Joplin_MO_64804', 'reason_code': 'COLOR', 'return_amount': Decimal('5.53'), 'quantity_returned': 1, 'return_condition': 'New', 'original_sale_id': 'SALE49110', 'original_sale_date': datetime.date(2025, 5, 22), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682289)}, {'return_id': 'RET000005', 'return_date': datetime.date(2025, 5, 12), 'product_id': '8ec10db6-3d52-4138-b', 'store_id': 'Auburn_Washington_98002', 'reason_code': 'COLOR', 'return_amount': Decimal('563.92'), 'quantity_returned': 4, 'return_condition': 'Used', 'original_sale_id': 'SALE14531', 'original_sale_date': datetime.date(2025, 5, 3), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682295)}, {'return_id': 'RET000006', 'return_date': datetime.date(2025, 5, 22), 'product_id': 'b9cf57c8-b12d-4843-8', 'store_id': 'Round Rock_Texas_78664', 'reason_code': 'PRICE', 'return_amount': Decimal('407.97'), 'quantity_returned': 3, 'return_condition': 'New', 'original_sale_id': 'SALE97083', 'original_sale_date': datetime.date(2025, 5, 5), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682301)}, {'return_id': 'RET000007', 'return_date': datetime.date(2025, 5, 17), 'product_id': 'f584b5e8-96e0-4380-9', 'store_id': 'Champaign_Illinois_61821', 'reason_code': 'DAMAGE', 'return_amount': Decimal('11.56'), 'quantity_returned': 2, 'return_condition': 'Used', 'original_sale_id': 'SALE47605', 'original_sale_date': datetime.date(2025, 5, 12), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682307)}, {'return_id': 'RET000008', 'return_date': datetime.date(2025, 4, 27), 'product_id': '870fa24f-e325-4f47-b', 'store_id': 'Redmond_Oregon_97756', 'reason_code': 'SIZE', 'return_amount': Decimal('3.08'), 'quantity_returned': 1, 'return_condition': 'Damaged', 'original_sale_id': 'SALE55651', 'original_sale_date': datetime.date(2025, 4, 21), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682314)}  ... displaying 10 of 200 total bound parameter sets ...  {'return_id': 'RET000199', 'return_date': datetime.date(2025, 5, 6), 'product_id': 'f7e643c9-d433-46a1-a', 'store_id': 'East Haven_Connecticut_6512', 'reason_code': 'COLOR', 'return_amount': Decimal('66.69'), 'quantity_returned': 3, 'return_condition': 'Damaged', 'original_sale_id': 'SALE98765', 'original_sale_date': datetime.date(2025, 4, 30), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 683310)}, {'return_id': 'RET000200', 'return_date': datetime.date(2025, 4, 27), 'product_id': '6fbbeae8-f22a-421e-b', 'store_id': 'Portsmouth_New Hampshire_3801', 'reason_code': 'OTHER', 'return_amount': Decimal('1282.56'), 'quantity_returned': 4, 'return_condition': 'New', 'original_sale_id': 'SALE85549', 'original_sale_date': datetime.date(2025, 4, 11), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 683315)})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-05-27T19:53:43.701+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=walmart_etl_dag, task_id=generate_inventory_returns, execution_date=20250527T195337, start_date=20250527T195343, end_date=20250527T195343
[2025-05-27T19:53:43.707+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 334 for task generate_inventory_returns ((psycopg2.errors.UndefinedColumn) column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^

[SQL: INSERT INTO ods_returns (return_id, return_date, product_id, store_id, reason_code, return_amount, quantity_returned, return_condition, original_sale_id, original_sale_date, source_system, load_timestamp) VALUES (%(return_id)s, %(return_date)s, %(product_id)s, %(store_id)s, %(reason_code)s, %(return_amount)s, %(quantity_returned)s, %(return_condition)s, %(original_sale_id)s, %(original_sale_date)s, %(source_system)s, %(load_timestamp)s)]
[parameters: ({'return_id': 'RET000001', 'return_date': datetime.date(2025, 4, 28), 'product_id': '26cf99d1-c6bd-461e-a', 'store_id': 'Albemarle_North Carolina_28001', 'reason_code': 'COLOR', 'return_amount': Decimal('25.12'), 'quantity_returned': 4, 'return_condition': 'New', 'original_sale_id': 'SALE91665', 'original_sale_date': datetime.date(2025, 4, 24), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682269)}, {'return_id': 'RET000002', 'return_date': datetime.date(2025, 5, 9), 'product_id': '284f26e1-172c-4007-a', 'store_id': 'Seguin_Texas_78155', 'reason_code': 'DEFECT', 'return_amount': Decimal('69.50'), 'quantity_returned': 5, 'return_condition': 'New', 'original_sale_id': 'SALE26945', 'original_sale_date': datetime.date(2025, 4, 11), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682277)}, {'return_id': 'RET000003', 'return_date': datetime.date(2025, 5, 21), 'product_id': 'edbadf2b-5c74-4ad2-a', 'store_id': 'State College_Pennsylvania_16801', 'reason_code': 'DAMAGE', 'return_amount': Decimal('504.45'), 'quantity_returned': 5, 'return_condition': 'Like New', 'original_sale_id': 'SALE58003', 'original_sale_date': datetime.date(2025, 5, 4), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682283)}, {'return_id': 'RET000004', 'return_date': datetime.date(2025, 5, 25), 'product_id': '4889f27d-999d-40f5-b', 'store_id': 'Joplin_MO_64804', 'reason_code': 'COLOR', 'return_amount': Decimal('5.53'), 'quantity_returned': 1, 'return_condition': 'New', 'original_sale_id': 'SALE49110', 'original_sale_date': datetime.date(2025, 5, 22), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682289)}, {'return_id': 'RET000005', 'return_date': datetime.date(2025, 5, 12), 'product_id': '8ec10db6-3d52-4138-b', 'store_id': 'Auburn_Washington_98002', 'reason_code': 'COLOR', 'return_amount': Decimal('563.92'), 'quantity_returned': 4, 'return_condition': 'Used', 'original_sale_id': 'SALE14531', 'original_sale_date': datetime.date(2025, 5, 3), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682295)}, {'return_id': 'RET000006', 'return_date': datetime.date(2025, 5, 22), 'product_id': 'b9cf57c8-b12d-4843-8', 'store_id': 'Round Rock_Texas_78664', 'reason_code': 'PRICE', 'return_amount': Decimal('407.97'), 'quantity_returned': 3, 'return_condition': 'New', 'original_sale_id': 'SALE97083', 'original_sale_date': datetime.date(2025, 5, 5), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682301)}, {'return_id': 'RET000007', 'return_date': datetime.date(2025, 5, 17), 'product_id': 'f584b5e8-96e0-4380-9', 'store_id': 'Champaign_Illinois_61821', 'reason_code': 'DAMAGE', 'return_amount': Decimal('11.56'), 'quantity_returned': 2, 'return_condition': 'Used', 'original_sale_id': 'SALE47605', 'original_sale_date': datetime.date(2025, 5, 12), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682307)}, {'return_id': 'RET000008', 'return_date': datetime.date(2025, 4, 27), 'product_id': '870fa24f-e325-4f47-b', 'store_id': 'Redmond_Oregon_97756', 'reason_code': 'SIZE', 'return_amount': Decimal('3.08'), 'quantity_returned': 1, 'return_condition': 'Damaged', 'original_sale_id': 'SALE55651', 'original_sale_date': datetime.date(2025, 4, 21), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 682314)}  ... displaying 10 of 200 total bound parameter sets ...  {'return_id': 'RET000199', 'return_date': datetime.date(2025, 5, 6), 'product_id': 'f7e643c9-d433-46a1-a', 'store_id': 'East Haven_Connecticut_6512', 'reason_code': 'COLOR', 'return_amount': Decimal('66.69'), 'quantity_returned': 3, 'return_condition': 'Damaged', 'original_sale_id': 'SALE98765', 'original_sale_date': datetime.date(2025, 4, 30), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 683310)}, {'return_id': 'RET000200', 'return_date': datetime.date(2025, 4, 27), 'product_id': '6fbbeae8-f22a-421e-b', 'store_id': 'Portsmouth_New Hampshire_3801', 'reason_code': 'OTHER', 'return_amount': Decimal('1282.56'), 'quantity_returned': 4, 'return_condition': 'New', 'original_sale_id': 'SALE85549', 'original_sale_date': datetime.date(2025, 4, 11), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 53, 43, 683315)})]
(Background on this error at: https://sqlalche.me/e/14/f405); 107)
[2025-05-27T19:53:43.720+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-27T19:53:43.735+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
