[2025-05-28T04:09:16.210+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-28T04:09:11+00:00 [queued]>
[2025-05-28T04:09:16.214+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-28T04:09:11+00:00 [queued]>
[2025-05-28T04:09:16.214+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-28T04:09:16.220+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_quality_checks> on 2025-05-28 04:09:11+00:00
[2025-05-28T04:09:16.223+0000] {standard_task_runner.py:57} INFO - Started process 288 to run task
[2025-05-28T04:09:16.225+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'data_quality_checks', 'manual__2025-05-28T04:09:11+00:00', '--job-id', '502', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmpcmhtdzae']
[2025-05-28T04:09:16.228+0000] {standard_task_runner.py:85} INFO - Job 502: Subtask data_quality_checks
[2025-05-28T04:09:16.252+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-28T04:09:11+00:00 [running]> on host 1a0764141710
[2025-05-28T04:09:16.417+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T04:09:11+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T04:09:11+00:00'
[2025-05-28T04:09:16.422+0000] {logging_mixin.py:154} INFO - Found 2 records in tgt_dim_product
[2025-05-28T04:09:16.422+0000] {logging_mixin.py:154} INFO - Found 2 records in tgt_dim_store
[2025-05-28T04:09:16.423+0000] {logging_mixin.py:154} INFO - Found 2 records in tgt_fact_sales
[2025-05-28T04:09:16.423+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_inventory
[2025-05-28T04:09:16.424+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_returns
[2025-05-28T04:09:16.424+0000] {logging_mixin.py:154} INFO - Found 0 historical product records
[2025-05-28T04:09:16.424+0000] {logging_mixin.py:154} INFO - Found 0 historical store records
[2025-05-28T04:09:16.425+0000] {python.py:194} INFO - Done. Returned value was: Data quality checks completed: {'tgt_dim_product': 2, 'tgt_dim_store': 2, 'tgt_fact_sales': 2, 'tgt_fact_inventory': 0, 'tgt_fact_returns': 0}
[2025-05-28T04:09:16.435+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=walmart_etl_dag, task_id=data_quality_checks, execution_date=20250528T040911, start_date=20250528T040916, end_date=20250528T040916
[2025-05-28T04:09:16.456+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-28T04:09:16.465+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
