[2025-05-27T22:23:45.022+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inventory_returns_generation.generate_all_inventory_returns manual__2025-05-27T22:23:43.610913+00:00 [queued]>
[2025-05-27T22:23:45.031+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inventory_returns_generation.generate_all_inventory_returns manual__2025-05-27T22:23:43.610913+00:00 [queued]>
[2025-05-27T22:23:45.031+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T22:23:45.039+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_all_inventory_returns> on 2025-05-27 22:23:43.610913+00:00
[2025-05-27T22:23:45.048+0000] {standard_task_runner.py:57} INFO - Started process 165 to run task
[2025-05-27T22:23:45.054+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'inventory_returns_generation', 'generate_all_inventory_returns', 'manual__2025-05-27T22:23:43.610913+00:00', '--job-id', '476', '--raw', '--subdir', 'DAGS_FOLDER/inventory_returns_dag.py', '--cfg-path', '/tmp/tmpmurya9i1']
[2025-05-27T22:23:45.060+0000] {standard_task_runner.py:85} INFO - Job 476: Subtask generate_all_inventory_returns
[2025-05-27T22:23:45.092+0000] {task_command.py:416} INFO - Running <TaskInstance: inventory_returns_generation.generate_all_inventory_returns manual__2025-05-27T22:23:43.610913+00:00 [running]> on host 096aa9233816
[2025-05-27T22:23:45.404+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inventory_returns_generation' AIRFLOW_CTX_TASK_ID='generate_all_inventory_returns' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T22:23:43.610913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T22:23:43.610913+00:00'
[2025-05-27T22:23:45.405+0000] {logging_mixin.py:154} INFO - Starting inventory and returns data generation...
[2025-05-27T22:23:45.405+0000] {logging_mixin.py:154} INFO - Retrieving existing data for inventory and returns generation...
[2025-05-27T22:23:45.419+0000] {logging_mixin.py:154} INFO - Generating inventory data...
[2025-05-27T22:23:45.428+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/walmart-etl/generate_inventory_returns_data.py", line 269, in main
    inventory_data = generate_inventory_data(existing_data, num_records=500)
  File "/opt/airflow/walmart-etl/generate_inventory_returns_data.py", line 120, in generate_inventory_data
    inventory_id = f"INV{uuid.uuid4().hex[:12]}"
NameError: name 'uuid' is not defined
[2025-05-27T22:23:45.435+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=inventory_returns_generation, task_id=generate_all_inventory_returns, execution_date=20250527T222343, start_date=20250527T222345, end_date=20250527T222345
[2025-05-27T22:23:45.442+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 476 for task generate_all_inventory_returns (name 'uuid' is not defined; 165)
[2025-05-27T22:23:45.488+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-27T22:23:45.507+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
